---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootybay-front
  namespace: bootybay
  labels:
    app: bootybay-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootybay-front
  template:
    metadata:
      labels:
        app: bootybay-front
    spec:
      imagePullSecrets:
        - name: docker-registry
      containers:
        - name: bootybay-front
          image: registry.ucandoit.io/bootybay-front:latest
          imagePullPolicy: Always
          ports:
            - name: http-entry
              protocol: TCP
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bootybay-front
  namespace: bootybay
  labels:
    app: bootybay-front
spec:
  type: ClusterIP
  ports:
    - name: http-entry
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: bootybay-front
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bootybay-front
  namespace: bootybay
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: bootybay.ucandoit.io
      http:
        paths:
          - path: /
            backend:
              serviceName: bootybay-front
              servicePort: 80
          # - path: /auctions
          #   backend:
          #     serviceName: bootybay-front
          #     servicePort: 80
